name: d3a-interface-ci
on:
  pull_request:
    branches:
      - master
      - staging
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        TOXENV: travis
      run: |
        pip install tox
        tox -e $TOXENV
