name: d3a-interface-ci-cd-development
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Trigger d3a deployment
      shell: bash
      run: |
        curl -X POST --header "authorization: Bearer ${{ secrets.GSYDEV_TOKEN }}" \
        -H 'Accept: application/json' \
        https://api.github.com/repos/gridsingularity/d3a-web/actions/workflows/d3a-development.yaml/dispatches \
        -d '{"ref":"refs/heads/master"}'
    - name: Trigger d3a-web deployment
      shell: bash
      run: |
        curl -X POST --header "authorization: Bearer ${{ secrets.GSYDEV_TOKEN }}" \
        -H 'Accept: application/json' \
        https://api.github.com/repos/gridsingularity/d3a-web/actions/workflows/d3a-web-development.yaml/dispatches \
        -d '{"ref":"refs/heads/master"}'
